include:
  - ./external-api/docker-compose-external-api.yaml

services:
  web:
    build:
      args:
        - NODEMON_VERSION=${NODEMON_VERSION:-3.1.7}
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/home/node/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
        restart: true
    networks:
      # - external-api_default
      - my-external-network
    
    # extra_hosts:
    # Permite que o container se comunique com a máquina host usando "host.docker.internal"
    # Isso é útil para acessar serviços que estão rodando na máquina host, como um banco de dados ou uma API.
    # necessario alterar o arquivo /etc/hosts do container para incluir a entrada "host.docker.internal" apontando para o ip 127.0.0.1

    # extra_hosts:
    #  - "host.docker.internal:host-gateway" 
   
  db:
    image: mysql:8.0.30-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s # com que frequencia o healthcheck será executado
      timeout: 5s # tempo máximo para o healthcheck responder
      retries: 5 # número de tentativas antes de considerar o serviço como unhealthy
      start_period: 10s # tempo de espera antes de iniciar o healthcheck, útil para serviços que demoram a iniciar
    networks: 
      # - external-api_default
      - my-external-network
    

# Se você quiser criar uma rede personalizada para seus serviços, pode usar a configuração abaixo.

networks:
  my-external-network:
    external: true


# Se você já tem uma rede externa criada, pode usar a configuração abaixo para conectar seus serviços a essa rede. 
# Certifique-se de substituir "external-api_default" pelo nome da sua rede externa.

# networks:
#  external-api_default:
#   external: true